version: '2.3'

services:
  mongo:
    image: mongo:4
    networks:
      - node_network
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
  server:
    build:
      context: .
      args:
        - NODE_ENV=development
    command: tsc-watch --onSuccess "node ./dist/server.js"
    depends_on:
      - mongo
    networks:
      - node_network
    ports:
      - 3000:3000
    volumes:
      - .:/opt/node_app/app:delegated
      - ./package.json:/opt/node_app/package.json
      - notused:/opt/node_app/app/node_modules
      - notused_dist:/opt/node_app/app/dist
volumes:
  mongo_data:
  notused:
  notused_dist:
networks:
  node_network: